version: 0.2
# based on the following AWS documentation:
# https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html
# https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-multi-architecture-image.html
# Verify the CodeBuild execution role can access ECR. 
# https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html
phases:
    install:
        commands:
            - yum update -y
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            - export DOCKER_BUILDKIT=1
            - docker build --platform=local -o . git://github.com/docker/buildx
            - mkdir -p ~/.docker/cli-plugins
            - mv buildx ~/.docker/cli-plugins/docker-buildx
            - docker buildx install

    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker image...      
            - export DOCKER_CLI_EXPERIMENTAL=enabled
            - docker version
            - docker build --platform "linux/amd64,linux/arm64" -t $IMAGE_REPO_NAME:$IMAGE_TAG .
            - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG